// Wortschatz vocabulary bank
// Each entry: [article, word, english, type, exampleDE, exampleEN]
// article is '' for non-nouns (verb/adjective/adverb/other); for those, `word` holds the term.
// Genders hand-checked. Example sentences are original (not from any dictionary).

const A2_WORDS = [
  // ---- People & relationships ----
  ["der","Mann","man","noun","Der Mann wartet an der Bushaltestelle.","The man is waiting at the bus stop."],
  ["die","Frau","woman","noun","Die Frau spricht drei Sprachen.","The woman speaks three languages."],
  ["das","Kind","child","noun","Das Kind malt ein Bild.","The child is drawing a picture."],
  ["der","Freund","friend (male)","noun","Mein Freund hilft mir beim Umzug.","My friend is helping me move."],
  ["die","Freundin","friend (female)","noun","Meine Freundin wohnt in Hamburg.","My friend lives in Hamburg."],
  ["der","Vater","father","noun","Mein Vater arbeitet im Krankenhaus.","My father works at the hospital."],
  ["die","Mutter","mother","noun","Meine Mutter backt sonntags einen Kuchen.","My mother bakes a cake on Sundays."],
  ["der","Bruder","brother","noun","Mein Bruder studiert in München.","My brother studies in Munich."],
  ["die","Schwester","sister","noun","Meine Schwester spielt Klavier.","My sister plays the piano."],
  ["die","Familie","family","noun","Die ganze Familie isst zusammen.","The whole family eats together."],
  ["der","Nachbar","neighbor","noun","Der Nachbar gießt meine Blumen.","The neighbor waters my flowers."],
  ["der","Mensch","human / person","noun","Jeder Mensch macht Fehler.","Every person makes mistakes."],
  ["das","Baby","baby","noun","Das Baby schläft endlich.","The baby is finally sleeping."],
  ["der","Chef","boss","noun","Mein Chef ist heute nicht im Büro.","My boss isn't in the office today."],
  ["der","Kollege","colleague","noun","Mein Kollege bringt morgen Kuchen mit.","My colleague is bringing cake tomorrow."],

  // ---- Home & everyday objects ----
  ["das","Haus","house","noun","Ihr Haus hat einen großen Garten.","Their house has a big garden."],
  ["die","Wohnung","apartment","noun","Die Wohnung liegt im dritten Stock.","The apartment is on the third floor."],
  ["das","Zimmer","room","noun","Mein Zimmer ist ziemlich klein.","My room is quite small."],
  ["die","Küche","kitchen","noun","In der Küche riecht es nach Kaffee.","The kitchen smells of coffee."],
  ["das","Bad","bathroom","noun","Das Bad wird gerade renoviert.","The bathroom is being renovated."],
  ["der","Tisch","table","noun","Auf dem Tisch liegt eine Zeitung.","There's a newspaper on the table."],
  ["der","Stuhl","chair","noun","Der Stuhl ist leider kaputt.","The chair is unfortunately broken."],
  ["das","Bett","bed","noun","Das Bett ist frisch bezogen.","The bed has fresh sheets."],
  ["die","Tür","door","noun","Mach bitte die Tür leise zu.","Please close the door quietly."],
  ["das","Fenster","window","noun","Durch das Fenster scheint die Sonne.","The sun shines through the window."],
  ["der","Schlüssel","key","noun","Ich finde meinen Schlüssel nicht.","I can't find my key."],
  ["die","Lampe","lamp","noun","Die Lampe im Flur ist kaputt.","The lamp in the hallway is broken."],
  ["der","Schrank","cupboard / wardrobe","noun","Die Teller sind im Schrank.","The plates are in the cupboard."],
  ["das","Sofa","sofa","noun","Die Katze schläft auf dem Sofa.","The cat sleeps on the sofa."],
  ["die","Uhr","clock / watch","noun","Die Uhr geht fünf Minuten vor.","The clock is five minutes fast."],

  // ---- Food & drink ----
  ["das","Wasser","water","noun","Trink bitte genug Wasser.","Please drink enough water."],
  ["der","Kaffee","coffee","noun","Der Kaffee ist noch zu heiß.","The coffee is still too hot."],
  ["der","Tee","tea","noun","Ich trinke abends gern Tee.","I like drinking tea in the evening."],
  ["das","Brot","bread","noun","Das Brot ist frisch vom Bäcker.","The bread is fresh from the bakery."],
  ["die","Milch","milk","noun","Die Milch ist leider sauer.","The milk has unfortunately gone sour."],
  ["der","Apfel","apple","noun","Der Apfel schmeckt schön süß.","The apple tastes nice and sweet."],
  ["das","Ei","egg","noun","Das Ei ist noch weich.","The egg is still soft."],
  ["der","Käse","cheese","noun","Der Käse riecht sehr stark.","The cheese smells very strong."],
  ["das","Fleisch","meat","noun","Sie isst kein Fleisch.","She doesn't eat meat."],
  ["das","Gemüse","vegetables","noun","Das Gemüse kommt aus dem Garten.","The vegetables come from the garden."],
  ["das","Obst","fruit","noun","Iss mehr Obst!","Eat more fruit!"],
  ["der","Zucker","sugar","noun","Nimmst du Zucker in den Kaffee?","Do you take sugar in your coffee?"],
  ["das","Salz","salt","noun","Reich mir bitte das Salz.","Please pass me the salt."],
  ["die","Suppe","soup","noun","Die Suppe ist noch zu heiß.","The soup is still too hot."],
  ["das","Essen","food / meal","noun","Das Essen ist fertig!","The meal is ready!"],

  // ---- Time ----
  ["die","Zeit","time","noun","Ich habe heute leider keine Zeit.","Unfortunately I have no time today."],
  ["der","Tag","day","noun","Der Tag war lang und anstrengend.","The day was long and tiring."],
  ["die","Woche","week","noun","Nächste Woche fahre ich weg.","Next week I'm going away."],
  ["der","Monat","month","noun","Der Monat vergeht so schnell.","The month is going by so fast."],
  ["das","Jahr","year","noun","Dieses Jahr lerne ich Deutsch.","This year I'm learning German."],
  ["die","Stunde","hour","noun","Der Film dauert zwei Stunden.","The film lasts two hours."],
  ["die","Minute","minute","noun","Warte bitte eine Minute.","Please wait a minute."],
  ["der","Morgen","morning","noun","Am Morgen trinke ich einen Kaffee.","In the morning I drink a coffee."],
  ["der","Abend","evening","noun","Der Abend war richtig gemütlich.","The evening was really cozy."],
  ["die","Nacht","night","noun","Die Nacht war kalt und still.","The night was cold and quiet."],
  ["der","Sommer","summer","noun","Im Sommer gehen wir oft schwimmen.","In summer we often go swimming."],
  ["der","Winter","winter","noun","Der Winter war dieses Jahr sehr mild.","The winter was very mild this year."],

  // ---- Places & travel ----
  ["die","Stadt","city","noun","Die Stadt ist am Wochenende voll.","The city is crowded on weekends."],
  ["das","Land","country / countryside","noun","Sie wohnt lieber auf dem Land.","She prefers living in the countryside."],
  ["die","Straße","street","noun","Die Straße ist wegen Bauarbeiten gesperrt.","The street is closed due to construction."],
  ["der","Weg","way / path","noun","Kannst du mir den Weg zeigen?","Can you show me the way?"],
  ["der","Bahnhof","train station","noun","Wir treffen uns am Bahnhof.","We'll meet at the train station."],
  ["der","Zug","train","noun","Der Zug hat zehn Minuten Verspätung.","The train is ten minutes late."],
  ["der","Bus","bus","noun","Der Bus kommt alle zwanzig Minuten.","The bus comes every twenty minutes."],
  ["das","Auto","car","noun","Das Auto springt nicht an.","The car won't start."],
  ["das","Fahrrad","bicycle","noun","Ich fahre mit dem Fahrrad zur Arbeit.","I ride my bike to work."],
  ["der","Flughafen","airport","noun","Der Flughafen ist weit außerhalb der Stadt.","The airport is far outside the city."],
  ["die","Reise","trip / journey","noun","Die Reise nach Wien war wunderschön.","The trip to Vienna was wonderful."],
  ["der","Urlaub","vacation","noun","Wir machen im August Urlaub.","We're going on vacation in August."],
  ["das","Hotel","hotel","noun","Das Hotel liegt direkt am Meer.","The hotel is right by the sea."],
  ["das","Ticket","ticket","noun","Hast du dein Ticket schon gekauft?","Have you bought your ticket yet?"],
  ["der","Platz","square / place / seat","noun","Ist dieser Platz noch frei?","Is this seat still free?"],

  // ---- Work, school, money ----
  ["die","Arbeit","work","noun","Die Arbeit macht mir meistens Spaß.","I mostly enjoy the work."],
  ["der","Beruf","profession","noun","Was bist du von Beruf?","What do you do for a living?"],
  ["das","Büro","office","noun","Ich sitze den ganzen Tag im Büro.","I sit in the office all day."],
  ["die","Schule","school","noun","Die Schule fängt um acht an.","School starts at eight."],
  ["die","Universität","university","noun","Sie studiert an der Universität Köln.","She studies at the University of Cologne."],
  ["das","Geld","money","noun","Für ein neues Auto fehlt das Geld.","There's no money for a new car."],
  ["der","Preis","price","noun","Der Preis ist wirklich zu hoch.","The price is really too high."],
  ["die","Rechnung","bill / invoice","noun","Können wir bitte die Rechnung haben?","Could we have the bill, please?"],
  ["das","Geschäft","shop / business","noun","Das Geschäft schließt um acht.","The shop closes at eight."],
  ["der","Markt","market","noun","Samstags gehe ich auf den Markt.","On Saturdays I go to the market."],

  // ---- Abstract / common nouns ----
  ["die","Idee","idea","noun","Das ist eine richtig gute Idee.","That's a really good idea."],
  ["das","Problem","problem","noun","Wir haben ein kleines Problem.","We have a small problem."],
  ["die","Frage","question","noun","Ich habe noch eine Frage.","I have one more question."],
  ["die","Antwort","answer","noun","Die Antwort war völlig falsch.","The answer was completely wrong."],
  ["die","Nachricht","message / news","noun","Ich habe deine Nachricht bekommen.","I got your message."],
  ["das","Gespräch","conversation","noun","Das Gespräch war sehr hilfreich.","The conversation was very helpful."],
  ["das","Wort","word","noun","Dieses Wort kenne ich noch nicht.","I don't know this word yet."],
  ["der","Grund","reason","noun","Es gibt keinen Grund zur Sorge.","There's no reason to worry."],
  ["das","Beispiel","example","noun","Gib mir bitte ein Beispiel.","Please give me an example."],
  ["die","Musik","music","noun","Die Musik ist mir zu laut.","The music is too loud for me."],

  // ---- Common verbs ----
  ["","gehen","to go","verb","Wir gehen heute Abend ins Kino.","We're going to the cinema tonight."],
  ["","kommen","to come","verb","Kommst du morgen zur Party?","Are you coming to the party tomorrow?"],
  ["","machen","to make / to do","verb","Was machst du am Wochenende?","What are you doing this weekend?"],
  ["","sehen","to see","verb","Ich sehe dich später am Bahnhof.","I'll see you later at the station."],
  ["","wissen","to know (a fact)","verb","Ich weiß die Antwort leider nicht.","Unfortunately I don't know the answer."],
  ["","kennen","to know (person/place)","verb","Kennst du ein gutes Restaurant hier?","Do you know a good restaurant here?"],
  ["","glauben","to believe / think","verb","Ich glaube, es wird gleich regnen.","I think it's going to rain soon."],
  ["","brauchen","to need","verb","Wir brauchen noch etwas Zeit.","We still need a little time."],
  ["","bleiben","to stay","verb","Bleib bitte noch ein bisschen.","Please stay a little longer."],
  ["","helfen","to help","verb","Kannst du mir kurz helfen?","Can you help me for a second?"],
  ["","verstehen","to understand","verb","Ich verstehe die Frage nicht ganz.","I don't quite understand the question."],
  ["","suchen","to look for","verb","Ich suche seit Tagen meine Brille.","I've been looking for my glasses for days."],
  ["","finden","to find","verb","Ich finde den Schlüssel nicht.","I can't find the key."],
  ["","treffen","to meet","verb","Wir treffen uns um sechs vor dem Café.","We're meeting at six in front of the café."],
  ["","bringen","to bring","verb","Bring bitte etwas zu trinken mit.","Please bring something to drink."],
  ["","kaufen","to buy","verb","Ich möchte ein neues Handy kaufen.","I want to buy a new phone."],
  ["","bezahlen","to pay","verb","Wer bezahlt heute das Essen?","Who's paying for the meal today?"],
  ["","essen","to eat","verb","Wir essen um sieben zu Abend.","We eat dinner at seven."],
  ["","trinken","to drink","verb","Sie trinkt morgens immer Tee.","She always drinks tea in the morning."],
  ["","schlafen","to sleep","verb","Das Kind schläft schon.","The child is already asleep."],
  ["","arbeiten","to work","verb","Er arbeitet von zu Hause aus.","He works from home."],
  ["","lernen","to learn","verb","Ich lerne gerade Deutsch.","I'm learning German right now."],
  ["","lesen","to read","verb","Abends lese ich gern ein Buch.","In the evening I like to read a book."],
  ["","schreiben","to write","verb","Ich schreibe ihr eine kurze Nachricht.","I'm writing her a short message."],
  ["","sprechen","to speak","verb","Sprichst du ein bisschen Englisch?","Do you speak a little English?"],
  ["","fahren","to drive / travel","verb","Wir fahren morgen nach Berlin.","We're travelling to Berlin tomorrow."],
  ["","spielen","to play","verb","Die Kinder spielen im Park.","The children are playing in the park."],
  ["","warten","to wait","verb","Warte bitte kurz auf mich.","Please wait for me a moment."],
  ["","fragen","to ask","verb","Darf ich dich etwas fragen?","May I ask you something?"],
  ["","antworten","to answer","verb","Sie antwortet nicht auf meine E-Mails.","She isn't answering my emails."],
  ["","öffnen","to open","verb","Kannst du das Fenster öffnen?","Can you open the window?"],
  ["","schließen","to close","verb","Bitte schließ die Tür.","Please close the door."],
  ["","beginnen","to begin","verb","Der Kurs beginnt nächste Woche.","The course begins next week."],
  ["","aufhören","to stop","verb","Hör bitte auf damit.","Please stop that."],
  ["","vergessen","to forget","verb","Vergiss deinen Schirm nicht.","Don't forget your umbrella."],
  ["","erzählen","to tell","verb","Erzähl mir von deinem Tag.","Tell me about your day."],
  ["","zeigen","to show","verb","Zeig mir bitte den Weg.","Please show me the way."],
  ["","versuchen","to try","verb","Ich versuche es noch einmal.","I'll try it once more."],
  ["","anrufen","to call (phone)","verb","Ruf mich heute Abend an.","Call me tonight."],
  ["","aufstehen","to get up","verb","Ich stehe unter der Woche früh auf.","I get up early on weekdays."],

  // ---- Common adjectives ----
  ["","groß","big / tall","adjective","Die Wohnung ist überraschend groß.","The apartment is surprisingly big."],
  ["","klein","small","adjective","Der Tisch ist zu klein für uns.","The table is too small for us."],
  ["","gut","good","adjective","Das Essen war richtig gut.","The food was really good."],
  ["","schlecht","bad","adjective","Das Wetter ist heute schlecht.","The weather is bad today."],
  ["","neu","new","adjective","Ich habe ein neues Fahrrad.","I have a new bike."],
  ["","alt","old","adjective","Das Haus ist über hundert Jahre alt.","The house is over a hundred years old."],
  ["","schön","beautiful / nice","adjective","Was für ein schöner Tag!","What a beautiful day!"],
  ["","teuer","expensive","adjective","Diese Uhr ist mir zu teuer.","This watch is too expensive for me."],
  ["","billig","cheap","adjective","Das Hotel war günstig und sauber.","The hotel was cheap and clean."],
  ["","schnell","fast","adjective","Der Zug ist sehr schnell.","The train is very fast."],
  ["","langsam","slow","adjective","Das Internet ist heute langsam.","The internet is slow today."],
  ["","wichtig","important","adjective","Das ist eine wichtige Frage.","That's an important question."],
  ["","einfach","easy / simple","adjective","Die Aufgabe war ganz einfach.","The task was quite easy."],
  ["","schwierig","difficult","adjective","Deutsch ist manchmal schwierig.","German is sometimes difficult."],
  ["","müde","tired","adjective","Ich bin heute sehr müde.","I'm very tired today."],
  ["","glücklich","happy","adjective","Sie sieht sehr glücklich aus.","She looks very happy."],
  ["","traurig","sad","adjective","Warum bist du so traurig?","Why are you so sad?"],
  ["","laut","loud","adjective","Die Nachbarn sind heute laut.","The neighbors are loud today."],
  ["","leise","quiet","adjective","Sprich bitte etwas leiser.","Please speak a bit more quietly."],
  ["","sauber","clean","adjective","Die Küche ist wieder sauber.","The kitchen is clean again."],
  ["","schmutzig","dirty","adjective","Deine Schuhe sind ganz schmutzig.","Your shoes are all dirty."],
  ["","warm","warm","adjective","Heute ist es angenehm warm.","Today it's pleasantly warm."],
  ["","kalt","cold","adjective","Mir ist kalt, mach bitte das Fenster zu.","I'm cold, please close the window."],
  ["","freundlich","friendly","adjective","Die Verkäuferin war sehr freundlich.","The saleswoman was very friendly."],
  ["","bequem","comfortable","adjective","Der Sessel ist wirklich bequem.","The armchair is really comfortable."],
  ["","pünktlich","punctual","adjective","Sei bitte pünktlich.","Please be on time."],
  ["","hungrig","hungry","adjective","Nach dem Sport bin ich immer hungrig.","After exercise I'm always hungry."],
  ["","krank","sick","adjective","Er ist seit gestern krank.","He has been sick since yesterday."],
  ["","gesund","healthy","adjective","Obst ist gesund.","Fruit is healthy."],
  ["","richtig","right / correct","adjective","Deine Antwort ist völlig richtig.","Your answer is completely correct."],

  // ---- Connectors & adverbs (A2-worth keeping) ----
  ["","vielleicht","maybe","other","Vielleicht komme ich etwas später.","Maybe I'll come a bit later."],
  ["","eigentlich","actually","other","Eigentlich wollte ich zu Hause bleiben.","Actually I wanted to stay home."],
  ["","deshalb","therefore","other","Es regnet, deshalb bleibe ich drinnen.","It's raining, so I'm staying inside."],
  ["","trotzdem","nevertheless","other","Es war teuer, trotzdem hat es sich gelohnt.","It was expensive, but it was worth it anyway."],
  ["","obwohl","although","other","Obwohl es spät war, gingen wir noch spazieren.","Although it was late, we still went for a walk."],
  ["","während","during / while","other","Während der Pause rufe ich dich an.","During the break I'll call you."],
  ["","zwischen","between","other","Das Café liegt zwischen Bank und Post.","The café is between the bank and the post office."],
  ["","außerdem","besides","other","Es ist teuer; außerdem gefällt es mir nicht.","It's expensive; besides, I don't like it."],
  ["","sofort","immediately","other","Ich komme sofort.","I'm coming right away."],
  ["","endlich","finally","other","Endlich ist Wochenende!","It's finally the weekend!"],
  ["","immer","always","other","Er kommt immer zu spät.","He's always late."],
  ["","manchmal","sometimes","other","Manchmal koche ich am Wochenende.","Sometimes I cook on the weekend."],
  ["","oft","often","other","Wir gehen oft spazieren.","We often go for walks."],
  ["","selten","rarely","other","Ich esse selten Fleisch.","I rarely eat meat."],
  ["","zusammen","together","other","Wir frühstücken am Sonntag zusammen.","We have breakfast together on Sunday."],
];

// B1 words are appended below in the next pass.
const B1_WORDS = [];

// Combined bank with level tags
const WORD_BANK = [
  ...A2_WORDS.map(w => ({ level: "A2", data: w })),
  ...B1_WORDS.map(w => ({ level: "B1", data: w })),
];

if (typeof module !== "undefined") { module.exports = { WORD_BANK, A2_WORDS, B1_WORDS }; }
